project:
  type: website
  output-dir: docs

website:
  title: "ManyDogs Project"
  favicon: images/favicon.ico
  navbar:
    left:
      - href: getinvolved.qmd
        text: Get Involved
      - text: "ManyDogs1"
        menu:
        - href: manydogs1.qmd
          text: Project
        - href: collaborators.qmd
          text: Collaborators
        - href: team.qmd
          text: Team
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

  page-footer: 
    background: light
    left: "&copy; 2023 ManyDogs. Powered by Quarto." 
    right: 
      - icon: github
        href: https://github.com/manydogsproject
      - icon: twitter 
        href: https://twitter.com/manydogsproject
      - icon: slack
        href: https://manydogsproject.slack.com/
      - icon: google
        href: https://groups.google.com/u/2/g/manydogs
      - icon: envelope
        href: manydogsproject@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



