project:
  type: website
  output-dir: docs
  resources: 
    - "lib/"
  render: 
    - "*.qmd"
    - "!call.qmd"
    - "!collaborators.qmd"
    - "!index_backup.qmd"
    - "!team.qmd"


website:
  title: "ManyDogs Project"
  favicon: images/favicon.ico
  navbar:
    left:
      - href: getinvolved.qmd
        text: Get Involved
      - text: Projects
        menu: 
        - href: manydogs1.qmd
          text: ManyDogs1
        - href: manydogs2.qmd
          text: ManyDogs2
      - href: publications.qmd
        text: Publications
      - href: leadership.qmd
        text: "Leadership Team"
      - href: contact.qmd
        text: Contact

  page-footer: 
    background: light
    left: "&copy; 2024 ManyDogs. Powered by Quarto." 
    right: 
      - icon: github
        href: https://github.com/manydogsproject
      - icon: twitter 
        href: https://twitter.com/manydogsproject
      - icon: mastodon 
        href: https://fediscience.org/@ManyDogs
      - icon: envelope
        href: mailto:manydogsproject@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



